services:
    veryshortlink:
        build: .
        ports:
            - "8082:8080"
        environment:
            - WEBSITE_URL = "https://lnk.ynis.fr"
        volumes:
        - type: bind
          source: ./data.db
          target: /usr/src/app/data.db
    